version: '3'

services:
  database:
    container_name: rustwebdev-postgres
    restart: always
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - rustwebdev-data:/var/lib/postgresql/data
      - ./data/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - 5432:5432
    networks:
      - rustwebdev-network
  server:
    restart: on-failure
    container_name: rustwebdev-webservice
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - ":3030:3030"
    networks:
      - rustwebdev-network
volumes:
  rustwebdev-data:
networks:
  rustwebdev-network:
