[package]
name = "handle-errors"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3.7"
tracing = { version = "0.1.40", features = ["log"] }
reqwest = "0.12.8"
reqwest-middleware = "0.3.3"
sqlx = "0.8.2"
rust-argon2 = "2.1.0"
